# Generated by Django 5.1.4 on 2025-01-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('site_consumption_grid_supply', models.FloatField()),
                ('site_consumption_natural_gas', models.FloatField()),
                ('onsite_solar_system_production', models.FloatField()),
                ('grid_price', models.FloatField()),
                ('ng_price', models.FloatField()),
            ],
        ),
    ]
