# Generated by Django 5.1.4 on 2024-12-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_consumption_grid_supply', models.DecimalField(decimal_places=2, max_digits=10)),
                ('site_consumption_natural_gas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('onsite_solar_system_production', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grid_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ng_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
