# Generated by Django 5.1.4 on 2024-12-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HourlyData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourlydata',
            name='day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hourlydata',
            name='hour',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hourlydata',
            name='month',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
