# Generated by Django 5.1.4 on 2024-12-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HourlyData', '0002_hourlydata_day_hourlydata_hour_hourlydata_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourlydata',
            name='grid_price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='hourlydata',
            name='ng_price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='hourlydata',
            name='onsite_solar_system_production',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='hourlydata',
            name='site_consumption_grid_supply',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='hourlydata',
            name='site_consumption_natural_gas',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
