# Generated by Django 5.1.4 on 2024-12-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HourlyData', '0003_alter_hourlydata_grid_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourlydata',
            name='grid_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hourlydata',
            name='ng_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hourlydata',
            name='onsite_solar_system_production',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hourlydata',
            name='site_consumption_grid_supply',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hourlydata',
            name='site_consumption_natural_gas',
            field=models.FloatField(),
        ),
    ]
