# Generated by Django 5.1.4 on 2024-12-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=30)),
                ('LCOE_instrument_cost', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
