# Generated by Django 5.1.4 on 2024-12-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstrumentCost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentcost',
            name='capacity_factor',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrumentcost',
            name='capex',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrumentcost',
            name='discount_rate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrumentcost',
            name='economic_life_year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrumentcost',
            name='fixed_om_cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrumentcost',
            name='fuel_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrumentcost',
            name='variable_om_cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
            preserve_default=False,
        ),
    ]
